### ISSUE TITLE
how to know which response

### ISSUE THREAD

**Issue by zh99998** [drbrain/net-http-pipeline#3]
``` ruby
require 'net/http/pipeline'

  Net::HTTP.start 'localhost' do |http|
    req1 = Net::HTTP::Get.new '/1'
    req2 = Net::HTTP::Get.new '/2'
    req3 = Net::HTTP::Get.new '/3'

    http.pipeline [req1, req2, req3] do |res|
      puts res.code
      puts res.body[0..60].inspect
      puts
    end
  end
```

then when I get a response, how to know which is it?

**Comment by drbrain** [comment]
RFC2616 says responses must be returned in the order they were issued, so /1 then /2 then /3.

The server and client are not allowed to change the order.

**Comment by zh99998** [comment]
no, i have tested nginx and github (gh-pages), they both not returning in order

**Comment by drbrain** [comment]
I can't reproduce with blog.rubygems.org (hosted on rubygems.github.com):

``` ruby
require 'net/http/pipeline'

http = Net::HTTP.new 'blog.rubygems.org'
http.pipelining = true # I know blog.rubygems.org supports pipelining
#http.set_debug_output $stderr # uncomment to verify pipelining behavior

http.start do |http|
  reqs = []
  reqs << Net::HTTP::Get.new('/')
  reqs << Net::HTTP::Get.new('/2013/02/08/2.0.0.rc.2-released.html')
  reqs << Net::HTTP::Get.new('/2013/01/31/data-verification.html')
  reqs << Net::HTTP::Get.new('/2012/12/03/2.0.0-preview2.html')

  http.pipeline reqs do |res|
    puts res.code
    puts res.body[/<title>(.*?)<\/title>/, 1]
    puts
  end
end
```

If you can provide a script I can reproduce with I will reopen to investigate, but I doubt there is anything I can do.  RFC 2616 says:

```
8.1.2.2 Pipelining

   A client that supports persistent connections MAY "pipeline" its
   requests (i.e., send multiple requests without waiting for each
   response). A server MUST send its responses to those requests in the
   same order that the requests were received.
```

So if a server does not return responses in-order you will need to contact the server vendor.

**Comment by zh99998** [comment]
oh...sorry...i'm wrong.
my logic was wrong...sorry...

**Comment by drbrain** [comment]
Ok, good to know.

Is there anything I can do to make the documentation more clear?

**Comment by zh99998** [comment]
in document demo, save request paths to an array, and when get a response, puts its path

**Comment by drbrain** [comment]
I added the above documentation change, but this really needs a full-up WEBrick example, most likely.

I will add one in the future.

Thank you for your comments!
